# Generated by Django 4.0.6 on 2022-08-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=500)),
                ('attribution', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Testimonial ',
                'verbose_name_plural': 'Testimonial s',
            },
        ),
    ]
